"""create mission_status enum and missions.status

Revision ID: 7f381f880fff
Revises: 
Create Date: 2025-10-27 16:12:16.050295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f381f880fff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resources')
    op.drop_index(op.f('ix_mission_resources_mission_id'), table_name='mission_resources')
    op.drop_index(op.f('ix_mission_resources_resource_id'), table_name='mission_resources')
    op.drop_table('mission_resources')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mission_resources',
    sa.Column('mission_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('resource_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('assigned_at', sa.DATETIME(), nullable=False),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_id', 'resource_id', name=op.f('uq_mission_resource'))
    )
    op.create_index(op.f('ix_mission_resources_resource_id'), 'mission_resources', ['resource_id'], unique=False)
    op.create_index(op.f('ix_mission_resources_mission_id'), 'mission_resources', ['mission_id'], unique=False)
    op.create_table('resources',
    sa.Column('type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('label', sa.VARCHAR(length=120), nullable=False),
    sa.Column('status', sa.VARCHAR(length=11), nullable=False),
    sa.Column('details', sa.TEXT(), nullable=True),
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    # ### end Alembic commands ###
